provider:
  name: faas
  gateway: http://127.0.0.1:8080

functions:
  radio:
    lang: go
    handler: ./radio
    image: docwareiy/radio:latest

  radio-sofia:
    lang: python3
    handler: ./radio-sofia
    image: docwareiy/radio-sofia:latest
